### ISSUE TITLE
Issues from morning session week 4

### ISSUE THREAD

**Issue by JauJau088** [GedeonTS/portfolio#9]
- We suggest changing the main javascript file name to something like main.js or index.js instead of menu.js for easier identification
- We suggest making only one template in HTML and making it responsive
- In Readme file, author section and contributors section, it is better to have not only the links to the social media but also the name of the person.
- For more concise javascript code, you can create functions for repeated actions

**Comment by GedeonTS** [comment]
thank you guys!
